# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: admin-service

on:
  push:
    branches:
      - main
    pull_request:
      branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: var

      - name: Set variables
        id: setvars
        run: |
          # Setup PROD Variables here
          if [[ "${{steps.var.outputs.branch}}" == "main" || "${{steps.var.outputs.branch}}" == *"feature"* ]]; then
            echo "REGION=us-east-1" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "REPO_ENV=npe" >> $GITHUB_ENV
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: AWS Credentials
        if: contains(steps.var.outputs.branch, 'release/') || contains(steps.var.outputs.branch, 'main')
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Check repoistory
        id: init
        if: contains(steps.var.outputs.branch, 'release/') || contains(steps.var.outputs.branch, 'main')
        run: |
          echo "Check repository for ${{ env.ENV }}  "
          if [[ "${{ env.ENV }}" == "dev" ]]; then
            aws ecr describe-repositories --repository-names weworks/npe/admin-service || aws ecr create-repository --repository-name weworks/npe/admin-service
          fi

      - name: Docker  Image Build
        if: contains(steps.var.outputs.branch, 'release/') || contains(steps.var.outputs.branch, 'main')
        run: |
          docker build  -t weworks/${{ env.REPO_ENV }}/admin-service:${{ github.run_number }} -f src/docker/Dockerfile .

      - name: Push docker image to AWS ECR
        if: contains(steps.var.outputs.branch, 'release/') || contains(steps.var.outputs.branch, 'main')
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ env.REGION }}
          image: weworks/${{ env.REPO_ENV }}/admin-service:${{ github.run_number }}
