# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: example-service

on:
  push:
    branches:
      - main
    pull_request:
      branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: var

      - name: Set variables
        id: setvars
        run: |
          # Setup PROD Variables here
          if [[ "${{steps.var.outputs.branch}}" == "main" || "${{steps.var.outputs.branch}}" == *"feature"* ]]; then
            echo "REGION=us-east-1" >> $GITHUB_ENV
            echo "ENV=dev" >> $GITHUB_ENV
            echo "REPO_ENV=npe" >> $GITHUB_ENV
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

